name: ci for probo fullstack

on:
  push:
    branches:
      - main

jobs:
  web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js for web
        uses: actions/setup-node@v1
        with:
          node-version: "22"

      - name: login in to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PROBO_DOCKERNAME }}
          password: ${{ secrets.PROBO_DOCKERPW }}

      - name: push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: pawan063/probofrontend

  api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js for api
        uses: actions/setup-node@v1
        with:
          node-version: "22"

      - name: login in to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PROBO_DOCKERNAME}}
          password: ${{ secrets.PROBO_DOCKERPW }}

      - name: push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: pawan063/probobackend

  worker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js for api
        uses: actions/setup-node@v1
        with:
          node-version: "22"
      - name: login in to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PROBO_DOCKERNAME}}
          password: ${{ secrets.PROBO_DOCKERPW }}
      - name: push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: pawan063/proboworker
  websockets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node.js for api
        uses: actions/setup-node@v1
        with:
          node-version: "22"
      - name: login in to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.PROBO_DOCKERNAME}}
          password: ${{ secrets.PROBO_DOCKERPW }}
      - name: push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: pawan063/probows
